### ISSUE TITLE
Highlight features based on the distance to the Wikidata entity location

### ISSUE THREAD

**Issue by planemad** [osmlab/wikidata-osm#2]
Since we have a distance field for each feature that indicates how far the corresponding Wikidata entity coordinates area, lets flag features with large distances visually. This will help focus on features that may have a potentially incorrect match.

Possible style ideas:
- Use stronger color for greater distances
- Use bigger marker size for greater distances

@amishas157 lets experiment and see what works better?

**Comment by planemad** [comment]
Possible distance buckets in km:
- 0 `Perfect`
- 0-0.1 
- 0.1-1 
- 1-5 
- 5-10
- 10+

**Comment by planemad** [comment]
Possible example to follow https://www.mapbox.com/mapbox-gl-js/example/data-driven-circle-colors/

**Comment by planemad** [comment]
For color ramps: http://tristen.ca/hcl-picker/#/hlc/6/1.07/773C32/E6FF6E

**Comment by planemad** [comment]
Used a simple green-yellow-red color scheme with circle size increasing with match distance. This is helping to quickly spot Wikidata matches possibly incorrect.

![screenshot 2016-11-24 16 25 45](https://cloud.githubusercontent.com/assets/126868/20596080/aff6cac8-b262-11e6-85b0-4eccf24bda8b.png)

**Comment by amishas157** [comment]
@planemad That looks great. Circle radius will be useful.

**Comment by planemad** [comment]
Done
