### ISSUE TITLE
OSM Wikidata code correct - Wikidata code matching is incorrect

### ISSUE THREAD

**Issue by DenisCarriere** [osmlab/wikidata-osm#9]
This is the inverse, the wikidata code in OSM is correct, but you're Wikidata code matching is incorrect.

### Khombole (14.7588, -16.6910) (lat,lng)
![image](https://cloud.githubusercontent.com/assets/550895/20634826/d9653a64-b322-11e6-93e4-fcc7f5c4d950.png)

https://osmlab.github.io/wikidata-osm/#9.82/14.6477/-16.6189
http://www.openstreetmap.org/node/3659463017
https://www.wikidata.org/wiki/Q2277705?uselang=en-US

**Comment by planemad** [comment]
@amishas157 the coordinate in Wikidata seems to match what is on OSM. Why is the distance so much?

**Comment by planemad** [comment]
@DenisCarriere looks like this was incorrect on Wikidata and fixed https://www.wikidata.org/w/index.php?title=Q2277705&type=revision&diff=394953745&oldid=374326537

The issue stems from using an outdated dump of Wikidata to do the location matches. It looks like the only way to get the latest location is by querying the Wikidata API.
